user root;
worker_processes auto;
pid /run/nginx.pid;
error_log /dev/stderr;

events {
    worker_connections 768;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    upstream ollama {
        server 127.0.0.1:11434;
    }

    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;

        location / {
            proxy_set_header Host "localhost";
            proxy_set_header X-Real-IP "127.0.0.1";
            proxy_set_header X-Forwarded-For "127.0.0.1";
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://ollama;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_cache_bypass $http_upgrade;
        }
    }
}
